version: 0.2

env:
  exported-variables:
    - IMAGE_TAG
    - REPOSITORY_URI
    - IMAGE_URI

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/sundar-brain-tasks
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG
      - echo IMAGE_URI=$IMAGE_URI

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $IMAGE_URI
      - echo Build completed successfully.
      - echo Image pushed: $IMAGE_URI