apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: brain-tasks-eks
  region: ap-south-1
  version: "1.34"

managedNodeGroups:
  - name: brain-tasks-ng
    instanceType: t3.small
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 20
